FIND_PATH(
  FFMPEG_INCLUDE_DIRS
  NAMES
    libavutil/avutil.h
    libavformat/avformat.h
    libavdevice/avdevice.h
    libswscale/swscale.h
    libavcodec/avfft.h
    libswresample/swresample.h
  PATHS
    ${FFMPEG_ROOT}/include
    /usr/local/include
  )

IF(NOT FFMPEG_INCLUDE_DIRS)
  MESSAGE(FATAL_ERROR "Could not find FFMPEG headers")
ENDIF()

FIND_LIBRARY(X264
  NAMES
  x264
  )

FIND_LIBRARY(ZLIB
  NAMES
  z
  )

FIND_LIBRARY(LZMA
  NAMES
  lzma
  )

FIND_LIBRARY(BZ2 bz2)
FIND_LIBRARY(DL dl)
FIND_LIBRARY(LZMA lzma)
FIND_LIBRARY(X11 X11)
FIND_LIBRARY(XEXT Xext)
FIND_LIBRARY(SDL SDL2)
FIND_LIBRARY(JACK jack)
FIND_LIBRARY(SNDIO sndio)
FIND_LIBRARY(XCBXFIX xcb-xfixes)
FIND_LIBRARY(XCBSHAPE xcb-shape)
FIND_LIBRARY(XV Xv)
FIND_LIBRARY(VDPAU vdpau)
FIND_LIBRARY(VAAPI va)
FIND_LIBRARY(VAX11 va-x11)
FIND_LIBRARY(VADRM va-drm)
FIND_LIBRARY(M m)
FIND_LIBRARY(Z z)
FIND_LIBRARY(OPUS opus)
FIND_LIBRARY(CORE_FOUNDATION CoreFoundation)
FIND_LIBRARY(CORE_MEDIA CoreMedia)
FIND_LIBRARY(CORE_VIDEO CoreVideo)
FIND_LIBRARY(VIDEO_DECODE_ACCELERATION VideoDecodeAcceleration)
FIND_LIBRARY(VIDEO_TOOL_BOX VideoToolBox)
FIND_LIBRARY(SECURITY Security)
FIND_LIBRARY(ICONV NAMES iconv)

IF (BZ2)
  LIST(APPEND OPTIONAL_LIBRARIES ${BZ2})
ENDIF()

IF (DL)
  LIST(APPEND OPTIONAL_LIBRARIES ${DL})
ENDIF()

IF (LZMA)
  LIST(APPEND OPTIONAL_LIBRARIES ${LZMA})
ENDIF()

IF (M)
  LIST(APPEND OPTIONAL_LIBRARIES ${M})
ENDIF()

IF (Z)
  LIST(APPEND OPTIONAL_LIBRARIES ${Z})
ENDIF()

IF (OPUS)
  LIST(APPEND OPTIONAL_LIBRARIES ${OPUS})
ENDIF()

IF (X11)
  LIST(APPEND OPTIONAL_LIBRARIES ${X11})
ENDIF()

IF (VAAPI)
  LIST(APPEND OPTIONAL_LIBRARIES ${VAAPI})
ENDIF()

IF (VADRM)
  LIST(APPEND OPTIONAL_LIBRARIES ${VADRM})
ENDIF()

IF (VAX11)
  LIST(APPEND OPTIONAL_LIBRARIES ${VAX11})
ENDIF()

IF (VDPAU)
  LIST(APPEND OPTIONAL_LIBRARIES ${VDPAU})
ENDIF()

IF(CORE_FOUNDATION)
  LIST(APPEND OPTIONAL_LIBRARIES ${CORE_FOUNDATION})
ENDIF()

IF(CORE_MEDIA)
  LIST(APPEND OPTIONAL_LIBRARIES ${CORE_MEDIA})
ENDIF()

IF(CORE_VIDEO)
  LIST(APPEND OPTIONAL_LIBRARIES ${CORE_VIDEO})
ENDIF()

IF(VIDEO_DECODE_ACCELERATION)
  LIST(APPEND OPTIONAL_LIBRARIES ${VIDEO_DECODE_ACCELERATION})
ENDIF()

IF(VIDEO_TOOL_BOX)
  LIST(APPEND OPTIONAL_LIBRARIES ${VIDEO_TOOL_BOX})
ENDIF()

IF(SECURITY)
  LIST(APPEND OPTIONAL_LIBRARIES ${SECURITY})
ENDIF()

IF(ICONV)
  LIST(APPEND OPTIONAL_LIBRARIES ${ICONV})
ENDIF()
FIND_LIBRARY(X11
  NAMES
  X11
  )

  IF (NOT X264)
    MESSAGE(FATAL_ERROR "Could not find FFMPEG x264")
  ENDIF()

  FIND_LIBRARY(MFX
    NAMES
    mfx
    )

  IF (MFX)
    LIST(APPEND FFMPEG_VIDEO_ENCODER ${MFX})
  ENDIF()

  FIND_LIBRARY(DL
    NAMES
    dl
    )

  LIST(APPEND FFMPEG_VIDEO_ENCODER ${X264})

FIND_LIBRARY(FFMPEG_LIBRARY_AVCODEC
  NAMES
    libavcodec.a
    avcodec
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_AVDEVICE
  NAMES
    avdevice
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_AVFILTER
  NAMES
    avfilter
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_AVFORMAT
  NAMES
    avformat
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_AVUTIL
  NAMES
    avutil
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_SWSCALE
  NAMES
    swscale
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_SWRESAMPLE
  NAMES
    swresample
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(FFMPEG_LIBRARY_POSTPROC
  NAMES
    postproc
  PATHS
    ${FFMPEG_ROOT}/lib
    /usr/local/lib
)

FIND_LIBRARY(BZ2 bz2)
FIND_LIBRARY(XCB xcb)
FIND_LIBRARY(XCB-SHM xcb-shm)
FIND_LIBRARY(ASOUND asound)
FIND_LIBRARY(DL dl)
FIND_LIBRARY(LZMA lzma)
FIND_LIBRARY(X11 X11)
FIND_LIBRARY(VDPAU vdpau)
FIND_LIBRARY(VAAPI va)
FIND_LIBRARY(VAX11 va-x11)
FIND_LIBRARY(VADRM va-drm)
FIND_LIBRARY(M m)
FIND_LIBRARY(Z z)
FIND_LIBRARY(OPUS opus)
FIND_LIBRARY(CORE_FOUNDATION CoreFoundation)
FIND_LIBRARY(CORE_MEDIA CoreMedia)
FIND_LIBRARY(CORE_VIDEO CoreVideo)
FIND_LIBRARY(VIDEO_DECODE_ACCELERATION VideoDecodeAcceleration)
FIND_LIBRARY(VIDEO_TOOL_BOX VideoToolBox)
FIND_LIBRARY(SECURITY Security)
FIND_LIBRARY(ICONV NAMES iconv)

IF (BZ2)
  LIST(APPEND OPTIONAL_LIBRARIES ${BZ2})
ENDIF()

IF (XCB)
  LIST(APPEND OPTIONAL_LIBRARIES ${XCB})
ENDIF()

IF (XCB-SHM)
  LIST(APPEND OPTIONAL_LIBRARIES ${XCB-SHM})
ENDIF()

IF (ASOUND)
  LIST(APPEND OPTIONAL_LIBRARIES ${ASOUND})
ENDIF()

IF (DL)
  LIST(APPEND OPTIONAL_LIBRARIES ${DL})
ENDIF()

IF (LZMA)
  LIST(APPEND OPTIONAL_LIBRARIES ${LZMA})
ENDIF()

IF (M)
  LIST(APPEND OPTIONAL_LIBRARIES ${M})
ENDIF()

IF (Z)
  LIST(APPEND OPTIONAL_LIBRARIES ${Z})
ENDIF()

IF (OPUS)
  LIST(APPEND OPTIONAL_LIBRARIES ${OPUS})
ENDIF()

IF (X11)
  LIST(APPEND OPTIONAL_LIBRARIES ${X11})
ENDIF()

IF (XEXT)
  LIST(APPEND OPTIONAL_LIBRARIES ${XEXT})
ENDIF()

IF (SDL)
  LIST(APPEND OPTIONAL_LIBRARIES ${SDL})
ENDIF()

IF (JACK)
  LIST(APPEND OPTIONAL_LIBRARIES ${JACK})
ENDIF()

IF (SNDIO)
  LIST(APPEND OPTIONAL_LIBRARIES ${SNDIO})
ENDIF()

IF (XCBXFIX)
  LIST(APPEND OPTIONAL_LIBRARIES ${XCBXFIX})
ENDIF()

IF (XCBSHAPE)
  LIST(APPEND OPTIONAL_LIBRARIES ${XCBSHAPE})
ENDIF()

IF (XV)
  LIST(APPEND OPTIONAL_LIBRARIES ${XV})
ENDIF()

IF (VAAPI)
  LIST(APPEND OPTIONAL_LIBRARIES ${VAAPI})
ENDIF()

IF (VADRM)
  LIST(APPEND OPTIONAL_LIBRARIES ${VADRM})
ENDIF()

IF (VAX11)
  LIST(APPEND OPTIONAL_LIBRARIES ${VAX11})
ENDIF()

IF (VDPAU)
  LIST(APPEND OPTIONAL_LIBRARIES ${VDPAU})
ENDIF()

IF(CORE_FOUNDATION)
  LIST(APPEND OPTIONAL_LIBRARIES ${CORE_FOUNDATION})
ENDIF()

IF(CORE_MEDIA)
  LIST(APPEND OPTIONAL_LIBRARIES ${CORE_MEDIA})
ENDIF()

IF(CORE_VIDEO)
  LIST(APPEND OPTIONAL_LIBRARIES ${CORE_VIDEO})
ENDIF()

IF(VIDEO_DECODE_ACCELERATION)
  LIST(APPEND OPTIONAL_LIBRARIES ${VIDEO_DECODE_ACCELERATION})
ENDIF()

IF(VIDEO_TOOL_BOX)
  LIST(APPEND OPTIONAL_LIBRARIES ${VIDEO_TOOL_BOX})
ENDIF()

IF(SECURITY)
  LIST(APPEND OPTIONAL_LIBRARIES ${SECURITY})
ENDIF()

IF(ICONV)
  LIST(APPEND OPTIONAL_LIBRARIES ${ICONV})
ENDIF()

SET(
  FFMPEG_LIBRARIES
  z
  ${OPTIONAL_LIBRARIES}
  ${FFMPEG_LIBRARY_AVFILTER}
  ${FFMPEG_LIBRARY_AVFORMAT}
  ${FFMPEG_LIBRARY_AVCODEC}
  ${FFMPEG_LIBRARY_AVDEVICE}
  ${FFMPEG_LIBRARY_AVUTIL}
  ${FFMPEG_LIBRARY_SWSCALE}
  ${FFMPEG_LIBRARY_SWRESAMPLE}
  ${FFMPEG_LIBRARY_POSTPROC}
  ${FFMPEG_VIDEO_ENCODER}
  ${DL}
  ${LZMA}
  ${X264}
  ${XCBSHM}
  )

IF(NOT FFMPEG_LIBRARIES)
  MESSAGE(FATAL_ERROR "Could not find FFMPEG libraries")
ENDIF()

INCLUDE_DIRECTORIES(${FFMPEG_INCLUDE_DIRS})
